### ISSUE TITLE
CRM Online Support?

### ISSUE THREAD

**Issue by DigitalFlow** [Akouddane/EasyPlugins#2]
Hey there,

nice looking project!
Did you need to use ILMerge for getting in the JS engines?
If yes, then this might possibly not work in CRM online with its sandbox, at least MS states it as not supported: https://blogs.msdn.microsoft.com/crm/2010/11/09/how-to-reference-assemblies-from-plug-ins/

Did you already try?

Kind Regards,
Florian

**Comment by Akouddane** [comment]
Hi Florian,
I didn't  have to use ILMerge because the JS Engine is totally included in the plugins project. No external DLLs are used.
The whole project was developped at first on CRM Online version 9.0, in sandbox mode.

You can give it a try, there is some simple examples on documentation page.

Thanks,
Amine
